#!/bin/sh

export OMII_CLIENT_HOME=.
export MY_CLASSPATH=.:${OMII_CLIENT_HOME}/lib:${OMII_CLIENT_HOME}/conf:
for j in `ls ${OMII_CLIENT_HOME}/lib/*.jar`; do
    MY_CLASSPATH=${j}:${MY_CLASSPATH}
done

echo Compiling the GridSAM client example...
javac -classpath ${MY_CLASSPATH} GridSAMExample.java
